# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VibenjiveUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('zipcode', models.CharField(max_length=5)),
                ('genres', models.CharField(max_length=100)),
                ('instruments', models.CharField(max_length=100)),
            ],
        ),
    ]
