# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibenjive', '0002_auto_20161006_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibenjiveuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
