# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibenjive', '0003_auto_20161104_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vibenjiveuser',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='vibenjiveuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vibenjiveuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vibenjiveuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='vibenjiveuser',
            name='password',
        ),
    ]
