# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibenjive', '0004_auto_20161117_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibenjiveuser',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
