# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibenjive', '0006_vibenjiveuser_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibenjiveuser',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
