# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibenjive', '0008_auto_20161129_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibenjiveuser',
            name='email',
            field=models.EmailField(default='live@live.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='vibenjiveuser',
            name='link',
            field=models.CharField(max_length=210, null=True),
        ),
    ]
