# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibenjive', '0010_auto_20161129_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('genre', models.CharField(max_length=30, unique=True)),
                ('instruments', models.CharField(max_length=30, unique=True)),
                ('url', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
