# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibenjive', '0011_usermusic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermusic',
            name='genre',
        ),
        migrations.AddField(
            model_name='usermusic',
            name='genres',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='usermusic',
            name='instruments',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usermusic',
            name='url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='usermusic',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
