# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibenjive', '0012_auto_20161205_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusic',
            name='title',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
