# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibenjive', '0013_usermusic_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermusic',
            name='id',
        ),
        migrations.AddField(
            model_name='usermusic',
            name='song_id',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
        ),
    ]
