# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibenjive', '0016_auto_20161205_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusic',
            name='zipcode',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
