# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibenjive', '0019_remove_vibenjiveuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermusic',
            name='title',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
